from collections import OrderedDict
from typing import Dict, List

from .models import Team


SCENARIO_PRESETS = {
    "balanced": {
        "label": "Balanced",
        "description": "Closest to the baseline power model with moderate upset variance.",
        "volatility": 0.18,
        "finishing": 1.0,
        "extra_time": 0.32,
    },
    "chalk": {
        "label": "Chalk",
        "description": "Compresses variance so the favorites advance more often.",
        "volatility": 0.08,
        "finishing": 0.94,
        "extra_time": 0.28,
    },
    "chaos": {
        "label": "Chaos",
        "description": "Boosts match-to-match randomness for a wilder tournament.",
        "volatility": 0.34,
        "finishing": 1.08,
        "extra_time": 0.36,
    },
}


TEAM_DATA = [
    {
        "code": "MEX",
        "name": "Mexico",
        "group": "A",
        "confederation": "Concacaf",
        "rating": 79,
        "attack": 78,
        "midfield": 76,
        "defense": 77,
        "keeper": 75,
        "form": 1.6,
        "style": "front-foot possession",
        "host": True,
    },
    {
        "code": "KOR",
        "name": "South Korea",
        "group": "A",
        "confederation": "AFC",
        "rating": 78,
        "attack": 76,
        "midfield": 77,
        "defense": 76,
        "keeper": 74,
        "form": 0.9,
        "style": "vertical press",
    },
    {
        "code": "RSA",
        "name": "South Africa",
        "group": "A",
        "confederation": "CAF",
        "rating": 71,
        "attack": 70,
        "midfield": 69,
        "defense": 70,
        "keeper": 72,
        "form": 0.8,
        "style": "transition attack",
    },
    {
        "code": "CZE",
        "name": "Czechia",
        "group": "A",
        "confederation": "UEFA",
        "rating": 77,
        "attack": 75,
        "midfield": 74,
        "defense": 76,
        "keeper": 76,
        "form": 0.5,
        "style": "direct buildup",
    },
    {
        "code": "CAN",
        "name": "Canada",
        "group": "B",
        "confederation": "Concacaf",
        "rating": 77,
        "attack": 77,
        "midfield": 75,
        "defense": 73,
        "keeper": 72,
        "form": 1.1,
        "style": "wide transition",
        "host": True,
    },
    {
        "code": "BIH",
        "name": "Bosnia and Herzegovina",
        "group": "B",
        "confederation": "UEFA",
        "rating": 74,
        "attack": 73,
        "midfield": 72,
        "defense": 72,
        "keeper": 71,
        "form": 0.6,
        "style": "countering blocks",
    },
    {
        "code": "QAT",
        "name": "Qatar",
        "group": "B",
        "confederation": "AFC",
        "rating": 72,
        "attack": 71,
        "midfield": 70,
        "defense": 69,
        "keeper": 70,
        "form": 0.4,
        "style": "patient circulation",
    },
    {
        "code": "SUI",
        "name": "Switzerland",
        "group": "B",
        "confederation": "UEFA",
        "rating": 81,
        "attack": 78,
        "midfield": 79,
        "defense": 80,
        "keeper": 80,
        "form": 0.7,
        "style": "compact control",
    },
    {
        "code": "BRA",
        "name": "Brazil",
        "group": "C",
        "confederation": "CONMEBOL",
        "rating": 92,
        "attack": 91,
        "midfield": 88,
        "defense": 85,
        "keeper": 85,
        "form": 1.2,
        "style": "fluid attacking",
    },
    {
        "code": "MAR",
        "name": "Morocco",
        "group": "C",
        "confederation": "CAF",
        "rating": 84,
        "attack": 81,
        "midfield": 80,
        "defense": 84,
        "keeper": 82,
        "form": 1.0,
        "style": "disciplined counter",
    },
    {
        "code": "HAI",
        "name": "Haiti",
        "group": "C",
        "confederation": "Concacaf",
        "rating": 68,
        "attack": 69,
        "midfield": 66,
        "defense": 65,
        "keeper": 65,
        "form": 0.7,
        "style": "open transition",
    },
    {
        "code": "SCO",
        "name": "Scotland",
        "group": "C",
        "confederation": "UEFA",
        "rating": 75,
        "attack": 74,
        "midfield": 73,
        "defense": 74,
        "keeper": 74,
        "form": 0.4,
        "style": "direct crossing",
    },
    {
        "code": "USA",
        "name": "United States",
        "group": "D",
        "confederation": "Concacaf",
        "rating": 80,
        "attack": 80,
        "midfield": 77,
        "defense": 76,
        "keeper": 75,
        "form": 0.8,
        "style": "athletic press",
        "host": True,
    },
    {
        "code": "PAR",
        "name": "Paraguay",
        "group": "D",
        "confederation": "CONMEBOL",
        "rating": 77,
        "attack": 74,
        "midfield": 75,
        "defense": 78,
        "keeper": 76,
        "form": 0.6,
        "style": "compact counter",
    },
    {
        "code": "AUS",
        "name": "Australia",
        "group": "D",
        "confederation": "AFC",
        "rating": 75,
        "attack": 73,
        "midfield": 74,
        "defense": 74,
        "keeper": 75,
        "form": 0.5,
        "style": "high-energy press",
    },
    {
        "code": "TUR",
        "name": "Turkiye",
        "group": "D",
        "confederation": "UEFA",
        "rating": 79,
        "attack": 78,
        "midfield": 76,
        "defense": 75,
        "keeper": 74,
        "form": 0.9,
        "style": "risk-on possession",
    },
    {
        "code": "GER",
        "name": "Germany",
        "group": "E",
        "confederation": "UEFA",
        "rating": 88,
        "attack": 86,
        "midfield": 85,
        "defense": 84,
        "keeper": 82,
        "form": 1.1,
        "style": "structured possession",
    },
    {
        "code": "CUR",
        "name": "Curacao",
        "group": "E",
        "confederation": "Concacaf",
        "rating": 69,
        "attack": 69,
        "midfield": 68,
        "defense": 66,
        "keeper": 66,
        "form": 0.8,
        "style": "wide overloads",
    },
    {
        "code": "CIV",
        "name": "Ivory Coast",
        "group": "E",
        "confederation": "CAF",
        "rating": 77,
        "attack": 78,
        "midfield": 74,
        "defense": 74,
        "keeper": 73,
        "form": 0.5,
        "style": "power transition",
    },
    {
        "code": "ECU",
        "name": "Ecuador",
        "group": "E",
        "confederation": "CONMEBOL",
        "rating": 80,
        "attack": 78,
        "midfield": 77,
        "defense": 78,
        "keeper": 77,
        "form": 0.7,
        "style": "counter press",
    },
    {
        "code": "NED",
        "name": "Netherlands",
        "group": "F",
        "confederation": "UEFA",
        "rating": 89,
        "attack": 88,
        "midfield": 86,
        "defense": 84,
        "keeper": 82,
        "form": 1.0,
        "style": "high-possession press",
    },
    {
        "code": "JPN",
        "name": "Japan",
        "group": "F",
        "confederation": "AFC",
        "rating": 83,
        "attack": 81,
        "midfield": 81,
        "defense": 80,
        "keeper": 79,
        "form": 1.0,
        "style": "automated movement",
    },
    {
        "code": "SWE",
        "name": "Sweden",
        "group": "F",
        "confederation": "UEFA",
        "rating": 76,
        "attack": 74,
        "midfield": 75,
        "defense": 75,
        "keeper": 75,
        "form": 0.6,
        "style": "set-piece control",
    },
    {
        "code": "TUN",
        "name": "Tunisia",
        "group": "F",
        "confederation": "CAF",
        "rating": 73,
        "attack": 71,
        "midfield": 70,
        "defense": 73,
        "keeper": 72,
        "form": 0.3,
        "style": "mid-block counter",
    },
    {
        "code": "BEL",
        "name": "Belgium",
        "group": "G",
        "confederation": "UEFA",
        "rating": 85,
        "attack": 84,
        "midfield": 83,
        "defense": 79,
        "keeper": 80,
        "form": 0.5,
        "style": "chance creation",
    },
    {
        "code": "IRN",
        "name": "Iran",
        "group": "G",
        "confederation": "AFC",
        "rating": 78,
        "attack": 75,
        "midfield": 76,
        "defense": 77,
        "keeper": 76,
        "form": 0.7,
        "style": "deep block breakouts",
    },
    {
        "code": "EGY",
        "name": "Egypt",
        "group": "G",
        "confederation": "CAF",
        "rating": 76,
        "attack": 76,
        "midfield": 73,
        "defense": 74,
        "keeper": 73,
        "form": 0.6,
        "style": "star-centric counter",
    },
    {
        "code": "NZL",
        "name": "New Zealand",
        "group": "G",
        "confederation": "OFC",
        "rating": 70,
        "attack": 68,
        "midfield": 68,
        "defense": 69,
        "keeper": 70,
        "form": 0.9,
        "style": "compact direct",
    },
    {
        "code": "ESP",
        "name": "Spain",
        "group": "H",
        "confederation": "UEFA",
        "rating": 94,
        "attack": 90,
        "midfield": 92,
        "defense": 88,
        "keeper": 85,
        "form": 1.1,
        "style": "positional dominance",
    },
    {
        "code": "CPV",
        "name": "Cape Verde",
        "group": "H",
        "confederation": "CAF",
        "rating": 72,
        "attack": 70,
        "midfield": 69,
        "defense": 70,
        "keeper": 70,
        "form": 0.8,
        "style": "compact counters",
    },
    {
        "code": "KSA",
        "name": "Saudi Arabia",
        "group": "H",
        "confederation": "AFC",
        "rating": 74,
        "attack": 73,
        "midfield": 72,
        "defense": 72,
        "keeper": 71,
        "form": 0.4,
        "style": "wide transitions",
    },
    {
        "code": "URU",
        "name": "Uruguay",
        "group": "H",
        "confederation": "CONMEBOL",
        "rating": 87,
        "attack": 85,
        "midfield": 83,
        "defense": 84,
        "keeper": 83,
        "form": 0.9,
        "style": "high-intensity counter press",
    },
    {
        "code": "FRA",
        "name": "France",
        "group": "I",
        "confederation": "UEFA",
        "rating": 93,
        "attack": 90,
        "midfield": 88,
        "defense": 87,
        "keeper": 86,
        "form": 1.0,
        "style": "elite transition",
    },
    {
        "code": "SEN",
        "name": "Senegal",
        "group": "I",
        "confederation": "CAF",
        "rating": 82,
        "attack": 80,
        "midfield": 79,
        "defense": 81,
        "keeper": 79,
        "form": 0.7,
        "style": "athletic pressing",
    },
    {
        "code": "IRQ",
        "name": "Iraq",
        "group": "I",
        "confederation": "AFC",
        "rating": 72,
        "attack": 71,
        "midfield": 69,
        "defense": 71,
        "keeper": 70,
        "form": 0.9,
        "style": "spirited counters",
    },
    {
        "code": "NOR",
        "name": "Norway",
        "group": "I",
        "confederation": "UEFA",
        "rating": 82,
        "attack": 85,
        "midfield": 79,
        "defense": 76,
        "keeper": 77,
        "form": 0.8,
        "style": "vertical finishing",
    },
    {
        "code": "ARG",
        "name": "Argentina",
        "group": "J",
        "confederation": "CONMEBOL",
        "rating": 95,
        "attack": 91,
        "midfield": 89,
        "defense": 88,
        "keeper": 86,
        "form": 1.2,
        "style": "controlled chance creation",
    },
    {
        "code": "ALG",
        "name": "Algeria",
        "group": "J",
        "confederation": "CAF",
        "rating": 77,
        "attack": 76,
        "midfield": 74,
        "defense": 74,
        "keeper": 73,
        "form": 0.5,
        "style": "quick combinations",
    },
    {
        "code": "AUT",
        "name": "Austria",
        "group": "J",
        "confederation": "UEFA",
        "rating": 80,
        "attack": 78,
        "midfield": 78,
        "defense": 77,
        "keeper": 76,
        "form": 0.6,
        "style": "ball-winning press",
    },
    {
        "code": "JOR",
        "name": "Jordan",
        "group": "J",
        "confederation": "AFC",
        "rating": 71,
        "attack": 70,
        "midfield": 69,
        "defense": 68,
        "keeper": 68,
        "form": 0.9,
        "style": "low-block transition",
    },
    {
        "code": "POR",
        "name": "Portugal",
        "group": "K",
        "confederation": "UEFA",
        "rating": 91,
        "attack": 89,
        "midfield": 87,
        "defense": 86,
        "keeper": 84,
        "form": 1.0,
        "style": "technical control",
    },
    {
        "code": "COD",
        "name": "DR Congo",
        "group": "K",
        "confederation": "CAF",
        "rating": 74,
        "attack": 75,
        "midfield": 72,
        "defense": 72,
        "keeper": 72,
        "form": 0.8,
        "style": "athletic transition",
    },
    {
        "code": "COL",
        "name": "Colombia",
        "group": "K",
        "confederation": "CONMEBOL",
        "rating": 85,
        "attack": 83,
        "midfield": 82,
        "defense": 81,
        "keeper": 80,
        "form": 0.9,
        "style": "counterpunch control",
    },
    {
        "code": "UZB",
        "name": "Uzbekistan",
        "group": "K",
        "confederation": "AFC",
        "rating": 74,
        "attack": 73,
        "midfield": 72,
        "defense": 72,
        "keeper": 71,
        "form": 0.8,
        "style": "compact verticality",
    },
    {
        "code": "ENG",
        "name": "England",
        "group": "L",
        "confederation": "UEFA",
        "rating": 92,
        "attack": 89,
        "midfield": 88,
        "defense": 86,
        "keeper": 84,
        "form": 0.9,
        "style": "set-piece volume",
    },
    {
        "code": "CRO",
        "name": "Croatia",
        "group": "L",
        "confederation": "UEFA",
        "rating": 86,
        "attack": 84,
        "midfield": 84,
        "defense": 82,
        "keeper": 80,
        "form": 0.7,
        "style": "midfield control",
    },
    {
        "code": "PAN",
        "name": "Panama",
        "group": "L",
        "confederation": "Concacaf",
        "rating": 71,
        "attack": 69,
        "midfield": 70,
        "defense": 69,
        "keeper": 69,
        "form": 0.5,
        "style": "compact pressing",
    },
    {
        "code": "GHA",
        "name": "Ghana",
        "group": "L",
        "confederation": "CAF",
        "rating": 74,
        "attack": 74,
        "midfield": 72,
        "defense": 71,
        "keeper": 72,
        "form": 0.7,
        "style": "direct dribbling",
    },
]


TEAM_FIFA_RANKS = {
    "FRA": 1,
    "ESP": 2,
    "ARG": 3,
    "ENG": 4,
    "POR": 5,
    "BRA": 6,
    "NED": 7,
    "MAR": 8,
    "BEL": 9,
    "GER": 10,
    "CRO": 11,
    "COL": 13,
    "SEN": 14,
    "MEX": 15,
    "USA": 16,
    "URU": 17,
    "JPN": 18,
    "SUI": 19,
    "IRN": 21,
    "TUR": 22,
    "ECU": 23,
    "AUT": 24,
    "KOR": 25,
    "AUS": 27,
    "ALG": 28,
    "EGY": 29,
    "CAN": 30,
    "NOR": 31,
    "PAN": 33,
    "CIV": 34,
    "SWE": 38,
    "PAR": 40,
    "CZE": 41,
    "SCO": 43,
    "TUN": 44,
    "COD": 46,
    "UZB": 50,
    "QAT": 55,
    "IRQ": 57,
    "RSA": 60,
    "KSA": 61,
    "JOR": 63,
    "BIH": 65,
    "CPV": 69,
    "GHA": 74,
    "CUR": 82,
    "HAI": 83,
    "NZL": 85,
}


TEAM_FLAG_CODES = {
    "ALG": "dz",
    "ARG": "ar",
    "AUS": "au",
    "AUT": "at",
    "BEL": "be",
    "BIH": "ba",
    "BRA": "br",
    "CAN": "ca",
    "COD": "cd",
    "COL": "co",
    "CPV": "cv",
    "CRO": "hr",
    "CUR": "cw",
    "CIV": "ci",
    "CZE": "cz",
    "ECU": "ec",
    "EGY": "eg",
    "ENG": "gb-eng",
    "ESP": "es",
    "FRA": "fr",
    "GER": "de",
    "GHA": "gh",
    "HAI": "ht",
    "IRN": "ir",
    "IRQ": "iq",
    "JOR": "jo",
    "JPN": "jp",
    "KOR": "kr",
    "KSA": "sa",
    "MAR": "ma",
    "MEX": "mx",
    "NED": "nl",
    "NOR": "no",
    "NZL": "nz",
    "PAN": "pa",
    "PAR": "py",
    "POR": "pt",
    "QAT": "qa",
    "RSA": "za",
    "SCO": "gb-sct",
    "SEN": "sn",
    "SUI": "ch",
    "SWE": "se",
    "TUN": "tn",
    "TUR": "tr",
    "URU": "uy",
    "USA": "us",
    "UZB": "uz",
}


RATINGS_CONTEXT = {
    "fieldSource": "FIFA confirmed World Cup 2026 field and completed 12-group draw.",
    "ratingSource": "FIFA Men's World Ranking snapshot dated 1 April 2026, anchored with squad-line priors.",
    "rankingDate": "2026-04-01",
}


def load_teams() -> List[Team]:
    teams = []
    for payload in TEAM_DATA:
        code = payload["code"]
        teams.append(
            Team(
                **payload,
                fifa_rank=TEAM_FIFA_RANKS[code],
                flag_code=TEAM_FLAG_CODES[code],
            )
        )
    return teams


def group_teams(teams: List[Team]) -> "OrderedDict[str, List[Team]]":
    grouped: "OrderedDict[str, List[Team]]" = OrderedDict()
    for team in teams:
        grouped.setdefault(team.group, []).append(team)
    return grouped


def tournament_metadata() -> Dict[str, object]:
    teams = load_teams()
    grouped = group_teams(teams)
    return {
        "name": "2026 World Cup Simulator",
        "format": "48 teams, 12 groups of four, top two plus eight best third-place teams advance.",
        "dates": "11 June 2026 to 19 July 2026",
        "fieldSource": RATINGS_CONTEXT["fieldSource"],
        "ratingSource": RATINGS_CONTEXT["ratingSource"],
        "rankingDate": RATINGS_CONTEXT["rankingDate"],
        "groups": [
            {
                "group": group_name,
                "teams": [team.to_summary() for team in group_teams_],
            }
            for group_name, group_teams_ in grouped.items()
        ],
        "teams": [team.to_summary() for team in sorted(teams, key=lambda item: item.name)],
        "scenarios": [
            {"id": key, **value}
            for key, value in SCENARIO_PRESETS.items()
        ],
        "defaults": {
            "iterations": 400,
            "scenario": "balanced",
            "hostAdvantage": True,
            "featuredTeam": "USA",
        },
    }
